// Конфигурация
const API_URL = 'http://localhost:3000';
const MAX_USERNAME_ATTEMPTS = 5;
const COMMON_PASSWORDS = ['password', '12345678', 'qwerty123', 'admin123', 'welcome1'];

// DOM элементы
const registerForm = document.getElementById('registerForm');
const loginForm = document.getElementById('loginForm');

// Инициализация
// document.addEventListener('DOMContentLoaded', function() {
//   if (registerForm) initRegistrationForm();
//   if (loginForm) initLoginForm();
// });

// Инициализация
document.addEventListener('DOMContentLoaded', function() {
  checkAuthState(); // Добавлена эта строка
  if (registerForm) initRegistrationForm();
  if (loginForm) initLoginForm();
});

// Проверка состояния авторизации
function checkAuthState() {
  const user = JSON.parse(sessionStorage.getItem('currentUser'));
  if (user && user.role === 'admin') {
    addAdminPanelLink();
  }
}

// Добавление кнопки админ-панели
function addAdminPanelLink() {
  const adminLink = document.getElementById('adminPanelLink');
  if (adminLink) {
    adminLink.style.display = 'block';
  }
}

function initRegistrationForm() {
  const passwordOptionRadios = document.querySelectorAll('input[name="passwordOption"]');
  const manualPasswordFields = document.querySelectorAll('.manual-password');
  const generateUsernameBtn = document.getElementById('generateUsername');
  const usernameInput = document.getElementById('username');
  const attemptsLeftSpan = document.getElementById('attemptsLeft');
  const registerBtn = document.getElementById('registerBtn');
  
  let usernameAttempts = MAX_USERNAME_ATTEMPTS;
  let isFormValid = false;
  let autoGeneratedPassword = generatePassword();

  // Переключение режима пароля
  passwordOptionRadios.forEach(radio => {
    radio.addEventListener('change', function() {
      const isManual = this.value === 'manual';
      manualPasswordFields.forEach(field => {
        field.style.display = isManual ? 'block' : 'none';
      });
      validateForm();
    });
  });

  // Генерация username
  generateUsernameBtn.addEventListener('click', generateUsername);
  
  function generateUsername() {
    if (usernameAttempts <= 0) {
      usernameInput.readOnly = false;
      generateUsernameBtn.disabled = true;
      usernameInput.placeholder = "Введите свой никнейм";
      return;
    }

    const firstName = document.getElementById('firstName').value.trim() || 'User';
    const lastName = document.getElementById('lastName').value.trim() || 'Name';
    
    const firstPart = firstName.slice(0, Math.min(3, firstName.length));
    const lastPart = lastName.slice(0, Math.min(3, lastName.length));
    const randomNum = Math.floor(Math.random() * 900) + 100;
    const separators = ['', '_', '.', '-'];
    const separator = separators[Math.floor(Math.random() * separators.length)];
    
    const generatedUsername = `${firstPart}${separator}${lastPart}${randomNum}`.toLowerCase();
    usernameInput.value = generatedUsername;
    usernameAttempts--;
    attemptsLeftSpan.textContent = usernameAttempts;
    
    checkUsernameAvailability(generatedUsername);
  }

  // Валидация в реальном времени
  registerForm.querySelectorAll('input').forEach(input => {
    input.addEventListener('input', function() {
      if (this.id === 'firstName' || this.id === 'lastName') {
        if (usernameAttempts > 0) generateUsername();
      }
      validateForm();
    });
  });

  // Обработка отправки формы
  registerForm.addEventListener('submit', async function(e) {
    e.preventDefault();
    if (!isFormValid) return;
    
    const password = document.querySelector('input[name="passwordOption"]:checked').value === 'auto' 
      ? autoGeneratedPassword 
      : document.getElementById('password').value;

    const userData = {
      firstName: document.getElementById('firstName').value,
      lastName: document.getElementById('lastName').value,
      middleName: document.getElementById('middleName').value || null,
      email: document.getElementById('email').value,
      phone: document.getElementById('phone').value,
      birthDate: document.getElementById('birthDate').value,
      username: document.getElementById('username').value,
      password: password,
      agreedToTerms: true,
      createdAt: new Date().toISOString(),
      role: 'customer'
    };

    try {
      const response = await fetch(`${API_URL}/users`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(userData),
      });

      if (response.ok) {
        alert('Регистрация успешна!');
        window.location.href = 'signin.html';
      } else {
        const errorData = await response.json();
        handleRegistrationError(errorData);
      }
    } catch (error) {
      console.error('Ошибка регистрации:', error);
      alert('Ошибка регистрации. Пожалуйста, попробуйте позже.');
    }
  });

  async function validateForm() {
    let isValid = true;
    
    // Проверка обязательных полей
    isValid = validateField('firstName', value => value.length >= 2) && isValid;
    isValid = validateField('lastName', value => value.length >= 2) && isValid;
    isValid = validateEmail() && isValid;
    isValid = validatePhone() && isValid;
    isValid = validateBirthDate() && isValid;
    isValid = await validateUsername() && isValid;
    isValid = validatePassword() && isValid;
    isValid = validateAgreement() && isValid;
    
    isFormValid = isValid;
    registerBtn.disabled = !isValid;
    return isValid;
  }

  function validateEmail() {
    const email = document.getElementById('email').value;
    const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!regex.test(email)) {
      showError('emailError', 'Введите корректный email');
      return false;
    }
    clearError('emailError');
    return true;
  }

  function validatePhone() {
    const phone = document.getElementById('phone').value;
    const regex = /^\+375(25|29|33|44)\d{7}$/;
    if (!regex.test(phone)) {
      showError('phoneError', 'Введите номер в формате +375XXXXXXXXX');
      return false;
    }
    clearError('phoneError');
    return true;
  }

  function validateBirthDate() {
    const birthDate = new Date(document.getElementById('birthDate').value);
    const minDate = new Date();
    minDate.setFullYear(minDate.getFullYear() - 16);
    
    if (birthDate > minDate) {
      showError('birthDateError', 'Вам должно быть не менее 16 лет');
      return false;
    }
    clearError('birthDateError');
    return true;
  }

  async function validateUsername() {
    const username = document.getElementById('username').value;
    if (!username) {
      showError('usernameError', 'Никнейм обязателен');
      return false;
    }
    
    try {
      const response = await fetch(`${API_URL}/users?username=${username}`);
      const users = await response.json();
      if (users.length > 0) {
        showError('usernameError', 'Этот никнейм уже занят');
        return false;
      }
    } catch (error) {
      console.error('Ошибка проверки никнейма:', error);
      return false;
    }
    
    clearError('usernameError');
    return true;
  }

  function validatePassword() {
    if (document.querySelector('input[name="passwordOption"]:checked').value === 'auto') {
      clearError('passwordError');
      clearError('repeatPasswordError');
      return true;
    }

    const password = document.getElementById('password').value;
    const repeatPassword = document.getElementById('repeatPassword').value;
    let isValid = true;

    if (password.length < 8 || password.length > 20) {
      showError('passwordError', 'Пароль должен быть 8-20 символов');
      isValid = false;
    } else if (!/[A-Z]/.test(password)) {
      showError('passwordError', 'Добавьте заглавную букву');
      isValid = false;
    } else if (!/[a-z]/.test(password)) {
      showError('passwordError', 'Добавьте строчную букву');
      isValid = false;
    } else if (!/[0-9]/.test(password)) {
      showError('passwordError', 'Добавьте цифру');
      isValid = false;
    } else if (!/[!@#$%^&*()]/.test(password)) {
      showError('passwordError', 'Добавьте спецсимвол');
      isValid = false;
    } else if (COMMON_PASSWORDS.includes(password.toLowerCase())) {
      showError('passwordError', 'Пароль слишком простой');
      isValid = false;
    } else {
      clearError('passwordError');
    }

    if (password !== repeatPassword) {
      showError('repeatPasswordError', 'Пароли не совпадают');
      isValid = false;
    } else {
      clearError('repeatPasswordError');
    }

    return isValid;
  }

  function validateAgreement() {
    if (!document.getElementById('agree').checked) {
      showError('agreeError', 'Необходимо согласие с правилами');
      return false;
    }
    clearError('agreeError');
    return true;
  }

  function generatePassword() {
    const uppercase = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
    const lowercase = 'abcdefghijkmnopqrstuvwxyz';
    const numbers = '23456789';
    const symbols = '!@#$%^&*';
    
    let password = '';
    password += getRandomChar(uppercase);
    password += getRandomChar(lowercase);
    password += getRandomChar(numbers);
    password += getRandomChar(symbols);
    
    const allChars = uppercase + lowercase + numbers + symbols;
    while (password.length < 12) {
      password += getRandomChar(allChars);
    }
    
    return password.split('').sort(() => Math.random() - 0.5).join('');
  }

  function getRandomChar(str) {
    return str[Math.floor(Math.random() * str.length)];
  }

  function showError(elementId, message) {
    const element = document.getElementById(elementId);
    element.textContent = message;
    element.style.display = 'block';
  }

  function clearError(elementId) {
    const element = document.getElementById(elementId);
    element.textContent = '';
    element.style.display = 'none';
  }

  function validateField(fieldId, validationFn, errorMessage = 'Обязательное поле') {
    const field = document.getElementById(fieldId);
    const value = field.value.trim();
    const errorElement = document.getElementById(`${fieldId}Error`);
    
    if (!value || !validationFn(value)) {
      showError(`${fieldId}Error`, errorMessage);
      return false;
    }
    clearError(`${fieldId}Error`);
    return true;
  }

  function handleRegistrationError(errorData) {
    if (errorData.email) showError('emailError', errorData.email);
    if (errorData.username) showError('usernameError', errorData.username);
    if (errorData.phone) showError('phoneError', errorData.phone);
  }

  // Первоначальная генерация
  generateUsername();
}

function initLoginForm() {
  loginForm.addEventListener('submit', async function(e) {
    e.preventDefault();
    
    const login = document.getElementById('login').value;
    const password = document.getElementById('password').value;

    try {
      const response = await fetch(`${API_URL}/users?email=${login}`);
      const users = await response.json();
      
      if (users.length === 0) {
        throw new Error('Неверный email или пароль');
      }

      const user = users[0];
      
      if (user.password !== password) {
        throw new Error('Неверный пароль');
      }

      // Сохраняем пользователя
      sessionStorage.setItem('currentUser', JSON.stringify(user));

      // Уведомление об успешном входе
      showSuccessMessage(`Добро пожаловать, ${user.firstName || user.username}!`);

      // Добавляем кнопку админа если нужно
      if (user.role === 'admin') {
        document.getElementById('adminPanelLink').style.display = 'block';
      }

      // Перенаправляем через 1.5 секунды (чтобы показать сообщение)
      setTimeout(() => {
        window.location.href = 'index.html';
      }, 1500);
      
    } catch (error) {
      showError('passwordError', error.message);
    }
  });
}

function showSuccessMessage(message) {
  const alertDiv = document.createElement('div');
  alertDiv.className = 'login-alert success';
  alertDiv.textContent = message;
  document.body.appendChild(alertDiv);
  
  setTimeout(() => {
    alertDiv.remove();
  }, 3000);
}